name: "*** build tipa file ***"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout Dopamine2-roothide
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Procursus
        uses: dhinakg/procursus-action@main
        with:
          packages: ldid findutils sed coreutils make

      - name: Install host dependencies
        run: |
          set -euxo pipefail
          brew update
          brew install openssl@3 libarchive

      - name: Install THEOS
        run: |
          set -euxo pipefail
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          mkdir -p "$THEOS"
          curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos -o install-theos.sh
          gsed -E "/^\s*get_theos\s*$/,+1 s/^(\s*)(get_sdks)\s*$/\1mkdir -p \${THEOS}\/sdks\n\1touch \${THEOS}\/sdks\/sdk\n\1\2/g" -i install-theos.sh
          bash install-theos.sh
          curl -L https://github.com/theos/sdks/releases/latest/download/iPhoneOS16.5.sdk.tar.xz -o "$THEOS/sdks/iPhoneOS16.5.sdk.tar.xz"
          gunzip "$THEOS/sdks/iPhoneOS16.5.sdk.tar.xz"
          tar -xf "$THEOS/sdks/iPhoneOS16.5.sdk.tar" -C "$THEOS/sdks"
          rm "$THEOS/sdks/iPhoneOS16.5.sdk.tar"
          cd "$BASEDIR"

      - name: Build and Install trustcache
        run: |
          set -euxo pipefail
          git clone https://github.com/CRKatri/trustcache
          cd trustcache
          export CFLAGS="$CFLAGS -I$(brew --prefix openssl)/include -arch arm64"
          export LDFLAGS="$LDFLAGS -L$(brew --prefix openssl)/lib -arch arm64"

          OPENSSL_PREFIX="$(brew --prefix openssl@3)"

          export CPPFLAGS="-I${OPENSSL_PREFIX}/include"
          export CFLAGS="-I${OPENSSL_PREFIX}/include"
          export LDFLAGS="-L${OPENSSL_PREFIX}/lib"
          export LIBRARY_PATH="${OPENSSL_PREFIX}/lib:${LIBRARY_PATH:-}"
          export CPATH="${OPENSSL_PREFIX}/include:${CPATH:-}"

          gmake -j"$(sysctl -n hw.physicalcpu)" OPENSSL=1
          install -m 755 trustcache /opt/procursus/bin/trustcache

      - name: Set Environment Variables
        run: |
          set -euxo pipefail
          T2=$(TZ=UTC-2 date +'%Y%m%d_%H%M%S')
          TS=$(date -j -f "%Y%m%d_%H%M%S" "${T2}" +%s)
          SHASH=$(git rev-parse --short HEAD)
          echo "ctime=${T2}" >> "$GITHUB_ENV"
          echo "ctimestamp=${TS}" >> "$GITHUB_ENV"
          echo "shorthash=${SHASH}" >> "$GITHUB_ENV"

      - name: Build Dopamine2-roothide
        run: |
          set -euxo pipefail
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"

          itemcount=$(plutil -extract items raw -expect array ./Application/Dopamine/UI/Settings/Credits.plist)
          for ((i=0; i<itemcount; i++)); do
            if [ "$(plutil -extract items.$i.headerCellClass raw ./Application/Dopamine/UI/Settings/Credits.plist)" = "DOCreditsCell" ]; then
              DOCreditsCellIndex=$i
            fi
          done

          plutil -insert items.$DOCreditsCellIndex.names -xml \
            "<dict><key>name</key><string>${{ github.actor }}</string><key>link</key><string>https://github.com/${{ github.repository }}</string></dict>" \
            -append ./Application/Dopamine/UI/Settings/Credits.plist
          rm -rf $(xcrun --sdk iphoneos --show-sdk-path)/usr/include/xpc $(xcrun --sdk iphoneos --show-sdk-path)/usr/include/xpc.modulemap
          gmake -j"$(sysctl -n hw.physicalcpu)" NIGHTLY=0
          mv ./Application/Dopamine.tipa ./Application/roothide-Dopamine2.tipa

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: roothide-Dopamine2.tipa
          path: Application/roothide-Dopamine2.tipa
